---
- name: version
  command: ssllabs-scan -version
  register: ssllabs_scan_installed_version
  changed_when: false
  failed_when: false

- block:
    - name: download
      get_url:
        url: "{{ ssllabs_scan_url }}"
        dest: /tmp
        checksum: "{{ ssllabs_scan_checksum }}"

    - block:
        - name: unarchive
          unarchive:
            src: "/tmp/{{ ssllabs_scan_pkg_ext }}"
            dest: /tmp
            remote_src: true
            creates: "{{ ssllabs_scan_bin }}"
        - name: executable bin for every user
          copy:
            src: "/tmp/{{ ssllabs_scan_pkg_bin }}"
            dest: "{{ ssllabs_scan_bin }}"
            remote_src: true
            owner: root
            group: root
            mode: '0755'
      become: true
  when: >
    ssllabs_scan_installed_version.stdout is not defined
    or ssllabs_scan_version not in ssllabs_scan_installed_version.stdout
